# Generated by Django 3.1.6 on 2021-02-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210207_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='description',
            field=models.CharField(choices=[('1', 'Hypergiant'), ('2', 'Supergiant'), ('3', 'Giant'), ('4', 'Subgiant'), ('5', 'Dwarf'), ('6', 'Subdwarf'), ('7', 'White Dwarf')], default='1', max_length=1),
        ),
    ]
