# Generated by Django 3.1.6 on 2021-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210207_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='size',
            field=models.CharField(choices=[('1', 'Giant Planet'), ('2', 'Ice Giant'), ('3', 'Mesoplanet'), ('4', 'Mini-Neptune'), ('5', 'Planetar'), ('6', 'Super-Earth'), ('7', 'Super-Jupiter'), ('8', 'Sub-Earth')], default='1', max_length=1),
        ),
    ]
