# Generated by Django 3.1.6 on 2021-02-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='age',
        ),
        migrations.AddField(
            model_name='star',
            name='description',
            field=models.CharField(choices=[('1', 'Hypergiants'), ('2', 'Supergiants'), ('3', 'Giants'), ('4', 'Subgiants'), ('5', 'Dwarf'), ('6', 'Subdwarf'), ('7', 'White Dwarf')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='star',
            name='solar_mass',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='star',
            name='spectral_type',
            field=models.CharField(choices=[('O', '0'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('K', 'K'), ('M', 'M')], default='O', max_length=1),
        ),
    ]
