# Generated by Django 3.1.6 on 2021-02-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210207_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(default='Enter Star Name', max_length=100),
        ),
    ]
