# Generated by Django 3.1.6 on 2021-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210207_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='size',
            new_name='mass',
        ),
        migrations.AddField(
            model_name='planet',
            name='orbit',
            field=models.CharField(choices=[('1', 'Circumbinary'), ('2', 'Exoplanet'), ('3', 'Goldilocks'), ('4', 'Pulsar'), ('5', 'Rogue')], default='1', max_length=1),
        ),
    ]
